  # User API
  /users/{uid}/labels:cache:
    get:
      tags:
        - User
      summary: 该接口用于灰度网关。获取指定 uid 用户灰度标签在指定 product 产品下的所有（未分页，最多 400 条）灰度标签，包括从 group 群组继承的灰度标签，按照 label 指派时间反序。网关只会取匹配 client 和 channel 的第一条。标签列表不是实时数据，会被服务缓存，缓存时间在 config.cache_label_expire 配置，默认为 1 分钟
      parameters:
        - in: path
          name: uid
          description: 用户 UID，当 uid 对应用户不存在时，该接口会返回空灰度标签列表
          required: true
          schema:
            type: string
        - in: query
          name: product
          description: 产品名称，当 product 对应产品不存在时，该接口会返回空灰度标签列表
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 请求成功
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      timestamp:
                        type: integer
                        format: int64
                        description: 灰度标签列表生成时间，1970 以来的秒数
                        example: 1585129360
                  - type: object
                    properties:
                      result:
                        type: array
                        description: 灰度标签列表
                        items:
                          $ref: "#/components/schemas/CacheLabelInfo"

  /v1/users/{uid}/labels:
    get:
      tags:
        - User
      summary: 获取指定 uid 用户所有灰度标签，不包括从群组继承的灰度标签，支持分页。考虑到灰度标签不会很多，暂未支持根据 product 过滤
      parameters:
        - in: header
          name: Authorization
          description: '请求 JWT token, 格式如: `Bearer xxx`'
          required: true
          schema:
            type: string
        - in: path
          name: uid
          description: 用户 UID，当 uid 对应用户不存在时，该接口会返回 404 错误
          required: true
          schema:
            type: string
        - in: query
          name: pageSize
          description: 分页大小，默认为 10，(1-1000]
          required: false
          schema:
            type: integer
            format: int32
            default: 10
            example: 20
        - in: query
          name: pageToken
          description: 分页请求标记，来自于响应结果的 nextPageToken
          required: false
          schema:
            title: pageToken
            type: string
            default: ""
            example: ""
      responses:
        '200':
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelsInfoRes'
        '401':
          description: 请求失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: 请求失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v1/users/{uid}/labels:cache:
    put:
      tags:
        - User
      summary: 强制刷新指定用户的灰度标签列表缓存
      parameters:
        - in: header
          name: Authorization
          description: '请求 JWT token, 格式如: `Bearer xxx`'
          required: true
          schema:
            type: string
        - in: path
          name: uid
          description: 用户 UID，当 uid 对应用户不存在时，该接口会返回 404 错误
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoolRes'
        '401':
          description: 请求失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: 请求失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v1/users/{uid}/labels:
    get:
      tags:
        - User
      summary: 获取指定 uid 用户所有灰度标签，不包括从群组继承的灰度标签，支持分页。考虑到灰度标签不会很多，暂未支持根据 product 过滤
      parameters:
        - in: header
          name: Authorization
          description: '请求 JWT token, 格式如: `Bearer xxx`'
          required: true
          schema:
            type: string
        - in: path
          name: uid
          description: 用户 UID，当 uid 对应用户不存在时，该接口会返回 404 错误
          required: true
          schema:
            type: string
        - in: query
          name: pageSize
          description: 分页大小，默认为 10，(1-1000]
          required: false
          schema:
            type: integer
            format: int32
            default: 10
            example: 20
        - in: query
          name: pageToken
          description: 分页请求标记，来自于响应结果的 nextPageToken
          required: false
          schema:
            title: pageToken
            type: string
            default: ""
            example: ""
      responses:
        '200':
          description: 请求成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabelsInfoRes'
        '401':
          description: 请求失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: 请求失败
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

      # requestBody:
      #   content:
      #     application/json:
      #       schema:
      #         $ref: '#/components/schemas/createCommentRequest'
      #   description: 动态信息
      #   required: true
