addr: ":3000"
logger:
  level: debug
mysql:
  host: localhost:3306
  user: root
  password: password
  database: urbs
  parameters: loc=UTC&readTimeout=10s&writeTimeout=10s&timeout=10s&multiStatements=false
  max_idle_conns: 8
  max_open_conns: 64
channels:
  - stable
  - beta
  - dev
clients:
  - web
  - ios
  - android
  - windows
  - macos
cache_label_expire: 1m