name: Urbs-Setting
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    # use mysql in VM https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
    - name: Try connect to MySQL and init datebase
      run: |
        mysql -hlocalhost -uroot -proot < ./sql/schema.sql

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Lint
      run: | # temporary fix. See https://github.com/actions/setup-go/issues/14
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u golang.org/x/lint/golint
        make lint

    - name: Test
      run: |
        CONFIG_FILE_PATH=${PWD}/config/test_on_github.yml APP_ENV=test go test -v ./...

    - name: Build
      run: make build
