name: Urbs-Setting
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    # services:
    #   mysql:
    #     image: mysql:5.7
    #     options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    #     env:
    #       MYSQL_ROOT_PASSWORD: password

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    # use mysql in VM https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
    - name: Try connect to MySQL and init datebase
      run: |
        mysql -hlocalhost -uroot -proot < ./sql/schema.sql

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Lint
      run: | # temporary fix. See https://github.com/actions/setup-go/issues/14
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u golang.org/x/lint/golint
        make lint

    - name: Test
      run: make test

    - name: Build
      run: make build
