name: Urbs-Setting Test
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    # use mysql in VM https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
    # https://github.com/actions/virtual-environments/issues/576
    - name: Try connect to MySQL and init datebase
      run: |
        export TZ=UTC
        sudo systemctl enable mysql.service
        sudo systemctl start mysql.service
        mysql -hlocalhost -uroot -proot < ./sql/schema.sql

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Lint
      run: | # temporary fix. See https://github.com/actions/setup-go/issues/14
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u golang.org/x/lint/golint
        make lint

    - name: Test
      run: |
        CONFIG_FILE_PATH=${PWD}/config/test_on_github.yml APP_ENV=test go test -v ./...
